Barebones events page
midiIT/midi2025 pull request #12
Opened 2024-11-08 16:36 UTC by AtomicTacoDev

Dar truksta keleto dalyku, bet pradziai veikia

2024-11-08 16:48 UTC, zhemepatis approved these changes
Manau, kad barebones task'ui visai zjbs

2024-11-08 16:48 UTC, zhemepatis commented on src/events.json
Kadangi turėsim daugiau duomenų (sponsoriai, komanda, galimai naujienos ir t.t. ir pan.), tai būtų visai nice turėti atskirą folderį tokiems dalykams

2024-11-09 10:22 UTC, midiIT requested changes
Kodas lyg ir good, siaip good job, bet 2 pastebejimai. Kodel savaites pirma diena sekmadienis:Dddd pakeiskit i pirmadieni, also, reiktu padaryt, kad tos datos kurios turi eventus butu gal light blue spalva nudazytos, nes dabar labai neaisku kada yra kokie eventai, ir tsg visas dienas clickini kol kazka parodo

2024-11-12 21:13 UTC, midiIT approved these changes

2024-11-12 21:13 UTC, midiIT commented on src/components/EventsPage/DatePicker.tsx
> +        console.log(daysArray)
istrinkit console.log ir galit merginti

2024-11-12 21:17 UTC, merged