24 ramune  katazauras
midiIT/midi2025 pull request #43
Opened 2024-11-28 16:16 UTC by ramuneri

2024-12-01 12:08 UTC, midiIT requested changes
Good job, tik keli changes yra

2024-12-01 12:08 UTC, midiIT commented on src/components/Games/Katazauras/GameKatazauras.tsx
> +  // const handleJump = () => { // only 1 jump
Komentara su nenaudojamu kodu reiktu istrinti

2024-12-01 12:08 UTC, midiIT commented on src/components/Games/Katazauras/GameKatazauras.tsx
> +    const updateGame = () => {
Sita funkcija reiktu iskelti is useEffect, ir tada prie dependencies prideti `updateGame`

2024-12-02 20:32 UTC, Kornelijus24 approved these changes
good
keli pastebėjimai ką būtų galima pridėti, pakeisti ateityje:
- kartais objektai spawninasi vienas ant kito
- vietoj alert pakeisti screen pačiam žaidime į game over
- pridėti kliūčių ore kažkokių ir greitinti nuo surinkto score, kad sunkiau būtų, nes dabar per lengva :D

2024-12-09 18:19 UTC, midiIT approved these changes

2024-12-10 09:58 UTC, merged